definitions:
  models.BusinessActivity:
    properties:
      doubtful_revenue:
        type: number
      hahal_revenue:
        type: integer
      halal:
        type: number
      not_halal:
        type: number
      not_halal_revenue:
        type: number
      questionable:
        type: number
      status:
        type: string
    type: object
  models.BussinessSummary:
    properties:
      lang:
        type: string
      last_updated:
        type: string
      source_filling_date:
        type: string
      source_filling_type:
        type: string
      ticker:
        type: string
      value:
        type: string
    type: object
  models.Data:
    properties:
      active:
        type: boolean
      bussiness_summary:
        $ref: '#/definitions/models.BussinessSummary'
      country:
        type: string
      currency:
        type: string
      description:
        type: string
      exchange:
        type: string
      expiration:
        type: integer
      group:
        type: string
      icon:
        type: string
      id:
        type: string
      identifiers:
        $ref: '#/definitions/models.Identifiers'
      is_buyable:
        type: boolean
      is_favorite:
        type: boolean
      is_sellabe:
        type: boolean
      key_stats:
        $ref: '#/definitions/models.KeyStats'
      mpi:
        type: string
      musaffa:
        $ref: '#/definitions/models.Musaffa'
      name:
        type: string
      option_data:
        $ref: '#/definitions/models.OptionData'
      purchase_statuses:
        items:
          $ref: '#/definitions/models.PurchaseStatuses'
        type: array
      ticker:
        type: string
      type:
        type: string
      underlying_symbol_id:
        type: string
    type: object
  models.Identifiers:
    properties:
      CUSIP:
        type: string
      FIGI:
        type: string
      ISIN:
        type: string
      RIC:
        type: string
      SEDOL:
        type: string
    type: object
  models.InterestBearingDebt:
    properties:
      amount:
        type: integer
      debtRatio:
        type: number
      status:
        type: string
    type: object
  models.InterestBearingSecuritiesAndAssets:
    properties:
      amount:
        type: integer
      interestRatio:
        type: number
      status:
        type: string
    type: object
  models.JsonFile:
    properties:
      data:
        $ref: '#/definitions/models.Data'
      description:
        type: string
      status:
        type: string
    type: object
  models.KeyStats:
    properties:
      average_daily_volume_for_last_10_days:
        type: string
      current_ratio:
        type: string
      dividient:
        type: integer
      dividient_per_share:
        type: string
      dividient_yield:
        type: string
      dividient_yield_ratio:
        type: integer
      eps:
        type: string
      l_t_debt_equility:
        type: string
      market_capitalization:
        type: string
      p_e:
        type: string
      price_change_1_day:
        type: string
      price_change_5_day:
        type: string
      quick_ratio:
        type: string
      roa:
        type: string
      roi:
        type: string
      total_debt_equity:
        type: string
    type: object
  models.Musaffa:
    properties:
      business_activity:
        $ref: '#/definitions/models.BusinessActivity'
      company_name:
        type: string
      compliance_ranking:
        type: integer
      id_musaffo:
        type: string
      interest_bearing_debt:
        $ref: '#/definitions/models.InterestBearingDebt'
      interest_bearing_securities_and_assets:
        $ref: '#/definitions/models.InterestBearingSecuritiesAndAssets'
      last_update:
        type: string
      report_date:
        type: string
      report_source:
        type: string
      shariah_compliance_status:
        type: string
      stock_name:
        type: string
      total_revenue:
        type: integer
      trailing_36_month_avr_cap:
        type: integer
    type: object
  models.OptionData:
    properties:
      option_group_id:
        type: string
      right:
        type: string
      strike_price:
        type: string
    type: object
  models.PurchaseStatuses:
    properties:
      count:
        type: integer
      pocket_id:
        type: string
      sell_count:
        type: integer
    type: object
  response.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.ResponseError:
    properties:
      error:
        $ref: '#/definitions/response.Error'
    type: object
  v1.Address:
    properties:
      City:
        type: string
      Country:
        type: string
      District:
        type: string
      PostalCode:
        type: string
      id:
        type: string
    type: object
  v1.CreateUserRequestBody:
    properties:
      Addresses:
        items:
          $ref: '#/definitions/v1.Address'
        type: array
      Status:
        type: string
      bio:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      phoneNumbers:
        items:
          type: string
        type: array
      post:
        items:
          $ref: '#/definitions/v1.Post'
        type: array
      typeId:
        type: integer
      updatedAt:
        type: string
      user_name:
        type: string
    type: object
  v1.EmailVer:
    properties:
      email:
        type: string
      email_code:
        type: string
    type: object
  v1.Media:
    properties:
      id:
        type: string
      link:
        type: string
      type:
        type: string
    type: object
  v1.Post:
    properties:
      createdAt:
        type: string
      id:
        type: string
      medias:
        items:
          $ref: '#/definitions/v1.Media'
        type: array
      name:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/get/json-resp:
    get:
      consumes:
      - application/json
      description: API for getting json data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JsonFile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResponseError'
      summary: get json data
      tags:
      - train
  /v1/users:
    get:
      consumes:
      - application/json
      description: This api is using for getting users list
      parameters:
      - description: limit
        in: path
        name: limit
        required: true
        type: integer
      - description: page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get user list
      tags:
      - user
  /v1/users/{id}:
    get:
      consumes:
      - application/json
      description: This api is using for getting user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get user
      tags:
      - user
  /v1/users/post:
    post:
      consumes:
      - application/json
      description: This api is using for creating new user
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.CreateUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create user
      tags:
      - user
  /v1/users/register:
    post:
      consumes:
      - application/json
      description: This api uses for registration new user
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.CreateUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Register User
      tags:
      - users
  /v1/users/verification:
    post:
      consumes:
      - application/json
      description: This api uses for sendin email code to user
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.EmailVer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Send Email Code
      tags:
      - users
swagger: "2.0"
